name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: "107.6.27.145"
          username: "root"
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
            cd /var/www/smartltc
            git pull